name = "ControlExamplePlots"
uuid = "5e0795ec-8005-5a21-beb4-c9685e7e8997"
authors = ["Dept. Automatic Control, Lund University"]
repo = "https://github.com/JuliaControl/ControlExamplePlots.jl.git"
version = "0.3.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
