name: ControlSystems PR Ping reciever

on: [repository_dispatch]

jobs:
  run-and-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PR ID
        if: github.event.action == 'prupdate' && github.event.sender.login == 'JuliaControlBot'
        run: |
          echo "PR id: '${{ github.event.client_payload.pr_number }}'
      - name: Plots and comment
        env:
          ACCESS_TOKEN_BOT: ${{ secrets.ACCESS_TOKEN_BOT }}
          PR_ID: ${{ github.event.client_payload.pr_number }}
          RUN_ID: ${{ github.run_id }}
        if: github.event.action == 'prupdate' && github.event.sender.login == 'JuliaControlBot'
        run: |
          echo "Got PR Update"
          echo "Verified user"
          xvfb-run julia ./utils/pr_commenter.jl
