name: ControlSystems PR Ping reciever
 
on: [repository_dispatch]
 
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Do stuff
        if: github.event.action == 'prupdate' && github.event.sender.login == 'JuliaControlBot'
        run: echo "Got PR Update" 
        run: echo "Verified user" 
        run: echo "Full event '${{ tojson(github.event) }}' "
